version: "3"

services:
  terra:
    image: terracotta
    container_name: MyTerra
    ports:
      - 8080:80
    volumes:
      - terra:/home
    working_dir: /home
    tty: true

volumes:
  terra:
    external: True