CREATE USER eoed WITH PASSWORD 'userEOEDs2';
CREATE DATABASE eoed_webapp;
GRANT ALL PRIVILEGES ON DATABASE eoed_webapp TO eoed;
USE eoed_webapp;
/*ALTER DATABASE eoed_webapp SET 'search_path' = public,shared_extension;*/
CREATE EXTENSION IF NOT EXISTS POSTGIS;
CREATE EXTENSION IF NOT EXISTS POSTGIS_TOPOLOGY;