version: "3"
services:
  web:
    image: django_image
    container_name: django
    ports:
      - "8888:8000"
    volumes:
      - web_app:/home
    working_dir: /home/web_app_base/django_base
    command: python manage.py runserver 0.0.0.0:8000